#!/usr/bin/env python

from control.maccontrol import MacControl
import logging
try:
    import daemon
except ImportError:
    logging.error("Unable to import 'daemon' please install python-daemon (apt-get install python-daemon)")
    exit()

CONFIG_FILE = 'maccontrol.conf'
LOG_FILE = '/var/log/maccontrol.log'
LOG_LEVEL = logging.INFO

with daemon.DaemonContext():
    logger = logging.getLogger('maccontrol')

    fh = logging.FileHandler(LOG_FILE)
    fh.setLevel(LOG_LEVEL)

    formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
    fh.setFormatter(formatter)

    logger.addHandler(fh)
    logger.setLevel(LOG_LEVEL)

    fc = MacControl(CONFIG_FILE)
    fc.run()
